// ═══════════════════════════════════════════════════════════════════
// CONTENT SET: IAAH — all iamalwayshungry.com projects (?set=iaah)
// Pulled from the IAAH DatoCMS; category = projectType (drives the tabs).
// ═══════════════════════════════════════════════════════════════════

export const SITE = { studio: 'IAAH', tagline: 'Creative Direction & Design' };

export const PROJECTS = [
  { client: 'GRISELDA', title: 'Main and Teaser Keyart', category: 'Commercial', year: 2024,
    image: 'content/iaah/griselda/00.jpg', images: ['content/iaah/griselda/00.jpg', 'content/iaah/griselda/01.jpg', 'content/iaah/griselda/02.jpg', 'content/iaah/griselda/03.jpg', 'content/iaah/griselda/04.jpg', 'content/iaah/griselda/05.jpg', 'content/iaah/griselda/06.jpg'],
    description: 'We partnered with Netflix to help develop and roll out a full campaign aimed at teasing the provocative subject matter at the heart of Griselda. The Queen Pin of Cocaine in the 70\'s-80\'s Miami. The six-part series stars Modern Family favo' },
  { client: 'FINESTKIND', title: 'Brand Development', category: 'Commercial', year: 2023,
    image: 'content/iaah/finestkind/00.jpg', images: ['content/iaah/finestkind/00.jpg', 'content/iaah/finestkind/01.jpg', 'content/iaah/finestkind/02.jpg', 'content/iaah/finestkind/03.jpg', 'content/iaah/finestkind/04.jpg', 'content/iaah/finestkind/05.jpg', 'content/iaah/finestkind/06.jpg', 'content/iaah/finestkind/07.jpg'],
    description: 'Development of title treatment, title sequence, and key art for the film Finestkind for Paramount. Finestkind tells the story of two half-brothers (Ben Foster and Toby Wallace), raised in different worlds, who are reunited as adults over a ' },
  { client: 'SQSP REBRAND', title: 'Brand Development', category: 'Commercial', year: 2023,
    image: 'content/iaah/sqsp-rebrand/00.jpg', images: ['content/iaah/sqsp-rebrand/00.jpg', 'content/iaah/sqsp-rebrand/01.jpg', 'content/iaah/sqsp-rebrand/02.jpg', 'content/iaah/sqsp-rebrand/03.jpg', 'content/iaah/sqsp-rebrand/04.jpg', 'content/iaah/sqsp-rebrand/05.jpg'],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aut' },
  { client: 'THE TRIAL', title: 'Design', category: 'Commercial', year: 2023,
    image: 'content/iaah/the-trial/00.jpg', images: ['content/iaah/the-trial/00.jpg', 'content/iaah/the-trial/01.jpg', 'content/iaah/the-trial/02.jpg', 'content/iaah/the-trial/03.jpg'],
    description: 'Thrilled to have done the interpretation of Orson Welles version of Frank Kafka\'s The Trial. The film is full of gorgeous cinematography, dizzying camera angles, and expressionistic lighting. Welles used increasingly surreal locations and ' },
  { client: 'WETRANSFER X OUTERNET', title: 'Brand Development', category: 'Commercial', year: 2022,
    image: 'content/iaah/wetransfer-x-outernet/00.jpg', images: ['content/iaah/wetransfer-x-outernet/00.jpg'],
    description: 'A partnership between the Outernet and WePresent. We partnered with the insanely talented group at Buck to develop a systematic approach to how WePresent editorial could be leveraged on the screens at the Outernet. A new immersive OOH exper' },
  { client: 'BURIAL', title: 'Design', category: 'Commercial', year: 2021,
    image: 'content/iaah/burial/00.jpg', images: ['content/iaah/burial/00.jpg', 'content/iaah/burial/01.jpg', 'content/iaah/burial/02.jpg', 'content/iaah/burial/03.jpg', 'content/iaah/burial/04.jpg'],
    description: 'This is not a Burial it\'s a Resurrection. We used this project as a starting point to stress test generative tooling and push the boundaries in typography.' },
  { client: 'KATLA', title: 'Design', category: 'Commercial', year: 2021,
    image: 'content/iaah/katla/00.jpg', images: ['content/iaah/katla/00.jpg', 'content/iaah/katla/01.jpg', 'content/iaah/katla/02.jpg', 'content/iaah/katla/03.jpg', 'content/iaah/katla/04.jpg', 'content/iaah/katla/05.jpg', 'content/iaah/katla/06.jpg', 'content/iaah/katla/07.jpg', 'content/iaah/katla/08.jpg', 'content/iaah/katla/09.jpg'],
    description: 'We developed the identity on Katla, a Netflix series that was centered on the active volcano Katla, in Iceland . Katla is an Icelandic mystery-drama series created by Baltasar Korm&aacute;kur and Sigurj&oacute;n Kjartansson . In the afterma' },
  { client: 'HOW TO  SELL DRUGS ONLINE FAST', title: 'Identity development', category: 'Commercial', year: 2020,
    image: 'content/iaah/how-to-sell-drugs-online-fast/00.jpg', images: ['content/iaah/how-to-sell-drugs-online-fast/00.jpg', 'content/iaah/how-to-sell-drugs-online-fast/01.jpg', 'content/iaah/how-to-sell-drugs-online-fast/02.jpg'],
    description: 'Partnered with Netflix to develop the identity and title sequence for the German-based show How to Sell Drugs Online Fast. The series is inspired by a true story that took place in Leipzig in 2015. Maximilian Schmidt, the inspiration for th' },
  { client: 'QUEENS GAMBIT', title: 'Identity development', category: 'Commercial', year: 2020,
    image: 'content/iaah/queens-gambit/00.jpg', images: ['content/iaah/queens-gambit/00.jpg', 'content/iaah/queens-gambit/01.jpg', 'content/iaah/queens-gambit/02.jpg', 'content/iaah/queens-gambit/03.jpg', 'content/iaah/queens-gambit/04.jpg'],
    description: 'Developed the identity for the break out hit \\"The Queen\'s Gambit\\" which follows the remarkable journey of Beth Harmon, a young orphaned chess prodigy, as she rises through the ranks of competitive chess in the 1950s and 1960s. The show' },
  { client: 'GRAND ARMY', title: 'Design', category: 'Commercial', year: 2019,
    image: 'content/iaah/grand-army/00.jpg', images: ['content/iaah/grand-army/00.jpg', 'content/iaah/grand-army/01.jpg', 'content/iaah/grand-army/02.jpg', 'content/iaah/grand-army/03.jpg', 'content/iaah/grand-army/04.jpg', 'content/iaah/grand-army/05.jpg', 'content/iaah/grand-army/06.jpg'],
    description: 'A powerful series that debuted on Netflix in 2020, We developed a series of marks and identities that we were very proud of that encapsulate New York and student life in a symbiotic nature. The series attempts to capture the various challen' },
  { client: 'DEAD MEN', title: 'Motion Studies', category: 'Commercial', year: 2018,
    image: 'content/iaah/dead-men/00.jpg', images: ['content/iaah/dead-men/00.jpg', 'content/iaah/dead-men/01.jpg', 'content/iaah/dead-men/02.jpg', 'content/iaah/dead-men/03.jpg', 'content/iaah/dead-men/04.jpg', 'content/iaah/dead-men/05.jpg', 'content/iaah/dead-men/06.jpg', 'content/iaah/dead-men/07.jpg', 'content/iaah/dead-men/08.jpg'],
    description: 'One of our favorite films of all time. We re-envisioned Jim Jarmusch\'s famous film through hand painted typography and selected stills. \\"Dead Man\\" is a wild west adventure where an accidental outlaw, William Blake, teams up with a Nati' },
  { client: 'SPEAK YOUR MIND', title: 'Design', category: 'Commercial', year: 2018,
    image: 'content/iaah/speak-your-mind/00.jpg', images: ['content/iaah/speak-your-mind/00.jpg', 'content/iaah/speak-your-mind/01.jpg', 'content/iaah/speak-your-mind/02.jpg', 'content/iaah/speak-your-mind/03.jpg', 'content/iaah/speak-your-mind/04.jpg', 'content/iaah/speak-your-mind/05.jpg', 'content/iaah/speak-your-mind/06.jpg', 'content/iaah/speak-your-mind/07.jpg', 'content/iaah/speak-your-mind/08.jpg', 'content/iaah/speak-your-mind/09.jpg', 'content/iaah/speak-your-mind/10.jpg'],
    description: '\\n Secret7 is a fundraising platform with an emphasis on participation and creation. In 2018 they focused on mental health and, as always, music. Squarespace came to us to concept and create a way for their partnership to be meaningful and' },
  { client: 'SQSP. MAKE IT.', title: 'Brand Development', category: 'Commercial', year: 2018,
    image: 'content/iaah/squarespace-make-itt/00.jpg', images: ['content/iaah/squarespace-make-itt/00.jpg'],
    description: 'Make it Beautiful. This campaign focused on the micro-interactions of how the web can guide and drive the movement of a website build. The narrative of each of the characters, what they are about and how it relates to their story was interw' },
  { client: 'SQUARESPACE - BUILD IT BEAUTIFUL', title: 'Brand Development', category: 'Commercial', year: 2017,
    image: 'content/iaah/squarespace-build-it-beautiful/00.jpg', images: ['content/iaah/squarespace-build-it-beautiful/00.jpg'],
    description: 'Build it Beautiful was a campaign developed to showcase Squarespace in it\'s simplest form, from its origins. The concept focused on showing a site built from its inception.' },
  { client: 'SPIDERMAN', title: 'Design', category: 'Commercial', year: 2012,
    image: 'content/iaah/spiderman/00.jpg', images: ['content/iaah/spiderman/00.jpg', 'content/iaah/spiderman/01.jpg', 'content/iaah/spiderman/02.jpg', 'content/iaah/spiderman/03.jpg', 'content/iaah/spiderman/04.jpg', 'content/iaah/spiderman/05.jpg', 'content/iaah/spiderman/06.jpg', 'content/iaah/spiderman/07.jpg', 'content/iaah/spiderman/08.jpg', 'content/iaah/spiderman/09.jpg', 'content/iaah/spiderman/10.jpg', 'content/iaah/spiderman/11.jpg', 'content/iaah/spiderman/12.jpg', 'content/iaah/spiderman/13.jpg', 'content/iaah/spiderman/14.jpg', 'content/iaah/spiderman/15.jpg', 'content/iaah/spiderman/16.jpg', 'content/iaah/spiderman/17.jpg', 'content/iaah/spiderman/18.jpg'],
    description: 'Exploration done for Marvel in preparation for several reapproaches of the Spiderman franchise. We were tasked with pushing the boundaries of what people knew and recognized Spiderman to be.' },
  { client: 'YOUNG GUNS 9', title: 'Design', category: 'Commercial', year: 2011,
    image: 'content/iaah/young-guns-9/00.jpg', images: ['content/iaah/young-guns-9/00.jpg', 'content/iaah/young-guns-9/01.jpg', 'content/iaah/young-guns-9/02.jpg', 'content/iaah/young-guns-9/03.jpg', 'content/iaah/young-guns-9/04.jpg', 'content/iaah/young-guns-9/05.jpg', 'content/iaah/young-guns-9/06.jpg', 'content/iaah/young-guns-9/07.jpg', 'content/iaah/young-guns-9/08.jpg', 'content/iaah/young-guns-9/09.jpg', 'content/iaah/young-guns-9/10.jpg'],
    description: '\\"Long after most punch the clock. And the take out gets cold. The playlist starts over. Again. After rounds 7,9, 9 ... and 14. My work and I are one. An attack on it is an attack on me. The crippling pressure to be better than the last be' },
  { client: 'ALPHABET SOUP', title: 'AI', category: 'Personal', year: 2024,
    image: 'content/iaah/alphabet-soup/00.jpg', images: ['content/iaah/alphabet-soup/00.jpg', 'content/iaah/alphabet-soup/01.jpg', 'content/iaah/alphabet-soup/02.jpg', 'content/iaah/alphabet-soup/03.jpg', 'content/iaah/alphabet-soup/04.jpg', 'content/iaah/alphabet-soup/05.jpg', 'content/iaah/alphabet-soup/06.jpg', 'content/iaah/alphabet-soup/07.jpg'],
    description: 'An ongoing typographic exploration meant to push the boundaries of textile, fashion, and typography.' },
  { client: 'BODY TYPE', title: 'AI', category: 'Personal', year: 2024,
    image: 'content/iaah/body-type/00.jpg', images: ['content/iaah/body-type/clip.mp4', 'content/iaah/body-type/00.jpg', 'content/iaah/body-type/01.jpg', 'content/iaah/body-type/02.jpg', 'content/iaah/body-type/03.jpg', 'content/iaah/body-type/04.jpg', 'content/iaah/body-type/05.jpg', 'content/iaah/body-type/06.jpg'],
    description: 'An exploration and investigation to how typography and body come together.' },
  { client: 'IAAH REEL 2024', title: 'AI', category: 'Personal', year: 2024,
    image: 'content/iaah/iaah-reel-2024/00.jpg', images: ['content/iaah/iaah-reel-2024/reel.mp4', 'content/iaah/iaah-reel-2024/00.jpg'],
    description: '' },
  { client: 'MOVEMENT', title: 'Design', category: 'Personal', year: 2023,
    image: 'content/iaah/movement/00.jpg', images: ['content/iaah/movement/00.jpg', 'content/iaah/movement/01.jpg', 'content/iaah/movement/02.jpg', 'content/iaah/movement/03.jpg', 'content/iaah/movement/04.jpg', 'content/iaah/movement/05.jpg', 'content/iaah/movement/06.jpg', 'content/iaah/movement/07.jpg'],
    description: 'A small series meant to play with movement, form, portrait, and typography.' },
  { client: 'NEUE FASHION', title: 'AI', category: 'Personal', year: 2023,
    image: 'content/iaah/neue-fashion/00.jpg', images: ['content/iaah/neue-fashion/00.jpg', 'content/iaah/neue-fashion/01.jpg', 'content/iaah/neue-fashion/02.jpg', 'content/iaah/neue-fashion/03.jpg', 'content/iaah/neue-fashion/04.jpg', 'content/iaah/neue-fashion/05.jpg'],
    description: 'Experimentation and play in type and new emergence in fashion.' },
  { client: 'THE CRITERION COLLECTION', title: 'Design', category: 'Personal', year: 2023,
    image: 'content/iaah/the-criterion-collection/00.jpg', images: ['content/iaah/the-criterion-collection/00.jpg', 'content/iaah/the-criterion-collection/01.jpg', 'content/iaah/the-criterion-collection/02.jpg', 'content/iaah/the-criterion-collection/03.jpg', 'content/iaah/the-criterion-collection/04.jpg', 'content/iaah/the-criterion-collection/05.jpg'],
    description: 'We have had the honor and privilege to have an ongoing relationship with the Criterion Collection since 2014. We\'ve developed many packages, box sets, and title treatments with and for the collection over the years.' },
  { client: 'THE LAST OF US', title: 'Design', category: 'Personal', year: 2023,
    image: 'content/iaah/the-last-of-us/00.jpg', images: ['content/iaah/the-last-of-us/00.jpg', 'content/iaah/the-last-of-us/01.jpg', 'content/iaah/the-last-of-us/02.jpg', 'content/iaah/the-last-of-us/03.jpg', 'content/iaah/the-last-of-us/04.jpg', 'content/iaah/the-last-of-us/05.jpg', 'content/iaah/the-last-of-us/06.jpg', 'content/iaah/the-last-of-us/07.jpg', 'content/iaah/the-last-of-us/08.jpg', 'content/iaah/the-last-of-us/09.jpg', 'content/iaah/the-last-of-us/10.jpg'],
    description: 'Done as a way to test the boundaries of what is possible through AI. We wanted to see how we could bring the break-out series the Last of Us to life through typography and image, embodying and conveying the series in a more vivid way.' },
  { client: 'TYPE AS FORM', title: 'Motion Studies', category: 'Personal', year: 2023,
    image: 'content/iaah/type-as-form/00.jpg', images: ['content/iaah/type-as-form/00.jpg', 'content/iaah/type-as-form/01.jpg', 'content/iaah/type-as-form/02.jpg', 'content/iaah/type-as-form/03.jpg', 'content/iaah/type-as-form/04.jpg', 'content/iaah/type-as-form/05.jpg'],
    description: 'Early experimentation with midjourney in which &lsquo;Hallucinations’ occurred. What are \\"Hallucinations within AI\\" - it\'s often seen as a system failures, mistakes, or lies. We need to remember that AI is not a fact-finder or a search' },
  { client: 'IAAH HEADERS', title: 'Motion Studies', category: 'Personal', year: 2017,
    image: 'content/iaah/iaah-headers/00.jpg', images: ['content/iaah/iaah-headers/00.jpg'],
    description: 'A series of typographic motion studies.' },
];

export const SETTINGS = {
  effect: 'lens-tunnel', scrollLerp: 0.05, smoothLerp: 0.06, maxVelocity: 40,
  autoScroll: true, autoSpeed: 60, autoResume: 2, trackBend: 1.0,
  audioSrc: null, audioVolume: 0.5, audioWarp: 1.0,
  beat: false, bpm: 60, beatAmount: 1.0, beatSharp: 4.0, beatStep: 80,
};
